version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/polyclinic-api?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vlad0316
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=polyclinic-api
      - MYSQL_ROOT_PASSWORD=Vlad0316
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s

volumes:
  mysql-data:
